<h2><strong>PANDA</strong></h2>  

In [1]:
import pandas as pd
#creating a datframe
x={'NAME':['rose','john','jane','mary'],'ID':[1,2,3,4],'SALARY':[1000,8000,5000,6000]}
df = pd.DataFrame(x)

In [2]:
df

NAME  ID  SALARY
0  rose   1    1000
1  john   2    8000
2  jane   3    5000
3  mary   4    6000

In [3]:
#Retrieving the 'ID' column and assigning it to a column
c=df[['ID']]
c

ID
0   1
1   2
2   3
3   4

In [4]:
#Access to multiply columns
z=df[['ID','SALARY']]
z

ID  SALARY
0   1    1000
1   2    8000
2   3    5000
3   4    6000

### SERIES METHODS (ATTRIBUTES)

In [5]:
print(df.values)

[['rose' 1 1000]
 ['john' 2 8000]
 ['jane' 3 5000]
 ['mary' 4 6000]]


In [6]:
print(df.index)

RangeIndex(start=0, stop=4, step=1)


In [7]:
print(df.size)

12


In [8]:
print('MEAN:',df[['SALARY']].mean())
print('SUM:',df[['SALARY']].sum())
print('MIN:',df[['SALARY']].min())
print('MAX:',df[['SALARY']].max())

MEAN: SALARY    5000.0
dtype: float64
SUM: SALARY    20000
dtype: int64
MIN: SALARY    1000
dtype: int64
MAX: SALARY    8000
dtype: int64


In [9]:
print(df[['NAME']].sort_values('NAME'))

   NAME
2  jane
1  john
3  mary
0  rose


In [10]:
print(df[['NAME']].sort_index())

   NAME
0  rose
1  john
2  jane
3  mary


In [11]:
#loc and iloc 
print(df.loc[3,'NAME'])
print(df.iloc[0,2])

mary
1000


## <strong> NUMPY </strong>

In [12]:
import numpy as np
#creating a numpy array
a =np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### METHODS

In [13]:
type(a) 

numpy.ndarray

In [14]:
a.dtype

dtype('int32')

In [15]:
# Selecting elements from index 0 to 6 with a step of 2
a[0:6:2]

array([0, 2, 4])

In [16]:
# Reversing the array
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### ATTRIBUTES

In [17]:
arr1= np.array([10,11,12,13,14,15])
arr2= np.array([20,21,22,23,24,24])

In [18]:
print('ADDITION:',np.add(arr1,arr2))
print('SUBTRACTION:',np.subtract(arr1,arr2))
print('MULTIPLY:',np.multiply(arr1,arr2))
print('DIVISION:',np.divide(arr1,arr2))
print('DOT:',np.dot(arr1,arr2))

ADDITION: [30 32 34 36 38 39]
SUBTRACTION: [-10 -10 -10 -10 -10  -9]
MULTIPLY: [200 231 264 299 336 360]
DIVISION: [0.5        0.52380952 0.54545455 0.56521739 0.58333333 0.625     ]
DOT: 1690


In [19]:
print(np.linspace(1,10,num=10)) 

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


### 2D NUMPY IN PYTHON

In [20]:
A = np.array([[0,1,1],[1,0,1]])
A

array([[0, 1, 1],
       [1, 0, 1]])